services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081" # Expose Mongo Express on port 8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb # Connect to the MongoDB service
      
  backend:
    build:
      context: ../booktable-backend
    container_name: booktable-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017

  frontend:
    build:
      context: ../frontend
    container_name: booktable-frontend
    ports:
      - "3000:80"  # Serve static frontend on port 3000 locally
    depends_on:
      - backend
    # no environment needed unless API_URL etc.

volumes:
  mongodb_data:
