### Book
POST http://127.0.0.1:8080/api/book
Content-Type: application/json

{
  "customerId": "67fdb6489fc4ac62aeb9eb5e",
  "restaurantId": "6813269bee172466f8574c21",
  "tableId": "6812ad85ca189206978c56d9",
  "startSlotTime": "11:00:00",
  "endSlotTime": "12:00:00",
  "date": "2025-04-23"
}

### Get all bookings
GET http://127.0.0.1:8080/api/book?startDate=2025-04-23&endDate=2025-04-23
Content-Type: application/json

### Get all bookings
GET http://localhost:8080/api/book?restaurantId=6813269bee172466f8574c21&startDate=2025-04-23&endDate=2025-04-23
Content-Type: application/json


