name: Terraform Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write  # Required for GitHub OIDC authentication for AWS
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Wait for manual approval
      uses: peter-evans/workflow-dispatch@v1
      with:
        workflow: 'Approve Terraform Plan'
        ref: ${{ github.ref }}
    
    - name: Terraform Apply
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: terraform apply -auto-approve tfplan

    - name: Output EC2 IPs
      run: |
        terraform output -json ec2_ips
